basePath: /
definitions:
  models.ExchangeRate:
    properties:
      Cur_Abbreviation:
        type: string
      Cur_ID:
        type: integer
      Cur_Name:
        type: string
      Cur_OfficialRate:
        type: number
      Cur_Scale:
        type: integer
      Date:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample exchange API.
  title: Exchange API
  version: "1.0"
paths:
  /rates:
    get:
      description: Get a list of all currency exchange rates.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ExchangeRate'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all currency rates
      tags:
      - rates
  /rates/{date}:
    get:
      description: Get currency exchange rates for a specific date in YYYY-MM-DD format.
      parameters:
      - description: Date in YYYY-MM-DD format
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ExchangeRate'
            type: array
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get currency rates by date
      tags:
      - rates
swagger: "2.0"
